name: style_component
description: Pond component for the style system.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_hooks: ^0.21.1-pre.0
  provider: ^6.0.5
  rxdart: ^0.27.5

  path_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.3"
      path: packages/path_core
  pond:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.3"
      path: packages/pond/pond
  style:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.3"
      path: packages/style
  utils:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.3"
      path: packages/utils/utils
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6
