name: task_core
description: Core module for running and scheduling tasks.

publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.6.0

version: 0.0.1

dependencies:
  collection: ^1.16.0
  cron: ^0.5.1

  actions_core:
    path: ../../../pond/modules/actions_core
  path_core:
    path: ../../../path_core
  pond_core:
    path: ../../../pond/pond_core
  utils_core:
    path: ../../../utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.6
