name: firebase_ops
description: Automate components to help with Firebase.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0

  drop_core:
    path: ../../../pond/modules/drop_core
  environment_core:
    path: ../../../pond/modules/environment_core
  persistence_core:
    path: ../../../persistence/persistence_core
  pond_cli:
    path: ../../../pond/pond_cli
  pond_core:
    path: ../../../pond/pond_core
  release:
    path: ../../../pond/modules/release
  runtime_type:
    path: ../../../type
  utils_core:
    path: ../../../utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6