name: firebase_ops
description: Automate components to help with Firebase.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0

  drop_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/drop_core
  environment_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/environment_core
  persistence_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/persistence/persistence_core
  pond_cli:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/pond_cli
  pond_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/pond_core
  release:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/release
  runtime_type:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/type
  utils_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6