name: example
description: Example for JLogical Utils.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  jlogical_utils:
    path: ../..

  flutter_hooks: ^0.18.0
  loading_overlay: 0.3.0
  path: ^1.8.0
  rxdart: ^0.27.1

flutter:
  uses-material-design: true

  assets:
    - assets/