name: example
description: Example for JLogical Utils.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.4.0

  intl: ^0.17.0
  meta: ^1.8.0
  provider: ^6.0.5

  jlogical_utils:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/jlogical_utils/jlogical_utils
  jlogical_utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/jlogical_utils/jlogical_utils_core
  jlogical_utils_cli:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/jlogical_utils/jlogical_utils_cli
flutter:
  uses-material-design: true

  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
dependency_overrides: # Needed because of [dcli] and [interact]
  intl: 0.18.0
  matcher: 0.12.14
  test_api: 0.4.16
  win32: 4.1.0
  path: 1.8.3
  js: 0.6.5
  posix: 5.0.0