name: example
description: Example for JLogical Utils.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_hooks: ^0.18.5+1
  meta: ^1.8.0
  provider: ^6.0.5

  jlogical_utils:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/jlogical_utils
  jlogical_utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/jlogical_utils_core

flutter:
  uses-material-design: true

  assets:
    - assets/
dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^1.3.3
dependency_overrides: # Needed because of [dcli] and [interact]
  intl: 0.18.0
  matcher: 0.12.14
  test_api: 0.4.16
  win32: 4.1.0
  path: 1.8.3
  js: 0.6.5