name: example
description: Example Flutter app using JLogical Utils.
publish_to: none
version: 0.0.4+2
environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.4.0
  collection: ^1.16.0
  intl: ^0.17.0
  meta: ^1.8.0
  provider: ^6.0.5
  jlogical_utils:
    git:
      url: "git@github.com:jaboyc/jlogical_utils.git"
      ref: v3.0
      path: packages/jlogical_utils/jlogical_utils
  example_core:
    path: ../example_core
flutter:
  uses-material-design: true
  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1
dependency_overrides:
  intl: 0.18.0
  win32: 4.1.0
  path: 1.8.3
  js: 0.6.5
  posix: 5.0.0
