name: example
description: Example Flutter app using Flood.
publish_to: none
version: 0.0.10+9
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.1-pre.0
  font_awesome_flutter: ^10.4.0
  collection: ^1.16.0
  intl: ^0.18.0
  meta: ^1.8.0
  provider: ^6.0.5
  flood:
    git:
      url: "git@github.com:JLogical-Apps/flood.git"
      ref: v4.0
      path: packages/flood/flood
  example_core:
    path: ../example_core
flutter:
  uses-material-design: true
  assets:
    - assets/
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7
dependency_overrides:
  http: 0.13.5
  vm_service: 13.0.0
