name: flood
repository: https://github.com/JLogical-Apps/flood

packages:
  - packages/**
  - example/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  test:
    name: test
    description: 'Tests every module'
    run: |
      melos exec --fail-fast                                  -- flutter analyze . && \
      melos exec --fail-fast --dir-exists="test" --no-flutter -- flutter test . && \
      melos exec --fail-fast --dir-exists="test" --flutter    -- flutter test .