name: jlogical_utils
description: Utils for JLogical.
version: 0.0.1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Presentation
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.0.0
  expandable: ^5.0.1
  flutter_colorpicker: ^0.5.0
  flutter_markdown: ^0.6.8
  flutter_picker: ^2.0.2
  google_fonts: ^2.1.0
  loading_overlay: ^0.3.0
  pull_to_refresh: ^2.0.0
  smooth_page_indicator: ^0.3.0-nullsafety.0
  tinycolor2: ^2.0.0
  transparent_image: ^2.0.0
  wave: ^0.2.0

  # Logging
  lumberdash: ^3.0.0
  colorize_lumberdash: ^3.0.0
  file_lumberdash: ^1.0.0

  # Application
  async: ^2.8.2
  cli_script: ^0.2.3+2
  dart_console: ^1.0.0
  dcli: ^1.16.2
  equatable: ^2.0.3
  flutter_bloc: ^7.0.1
  flutter_hooks: ^0.18.0
  flutter_mobx: ^2.0.0
  get_it: 7.2.0
  image: ^3.1.1
  interact: ^2.1.1
  process_run: ^0.12.3+2
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.2

  # Backend
  freezed_annotation: ^0.14.2
  intl: ^0.17.0
  json_serializable: ^4.1.3
  json2yaml: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.8
  rxdart: ^0.27.1
  synchronized: ^3.0.0
  uuid: ^3.0.4
  yaml: ^3.1.0

  # Firebase
  cloud_firestore: ^3.1.7
  firebase_analytics: ^9.1.0
  firebase_auth: ^3.3.6
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5 # flutter packages pub run build_runner watch
  freezed: ^0.14.2

flutter:
  uses-material-design: true