name: jlogical_utils
description: Utils for JLogical. 
version: 0.0.1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Presentation
  cached_network_image: ^3.0.0
  flutter_colorpicker: 0.4.0
  flutter_picker: ^2.0.2
  expandable: ^5.0.1
  loading_overlay: ^0.3.0
  pull_to_refresh: ^2.0.0
  transparent_image: ^2.0.0

  # Application
  flutter_bloc: ^7.0.1
  flutter_hooks: ^0.18.0
  equatable: ^2.0.3
  flutter_mobx: ^2.0.0
  provider: ^5.0.0
  url_launcher: ^6.0.2

  # Backend
  freezed_annotation: ^0.14.2
  intl: ^0.17.0
  json_serializable: ^4.1.3
  json2yaml: ^2.0.0
  path: ^1.8.0
  rxdart: ^0.27.1
  uuid: 3.0.4
  yaml: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.5 # flutter packages pub run build_runner watch
  freezed: ^0.14.2

flutter: