name: utils_core
description: The core utilities.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  path: ^1.8.2
  rxdart: ^0.27.5
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4