name: location
description: Flutter utils for getting the device's location.

publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.6.0

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^12.0.0
  rxdart: ^0.28.0

  drop:
    path: ../../../pond/modules/drop
  environment:
    path: ../../../pond/modules/environment
  location_core:
    path: ../../../pond/modules/location_core
  pond:
    path: ../../../pond/pond
  runtime_type:
    path: ../../../type
  style:
    path: ../../../style
  utils:
    path: ../../../utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
