name: location
description: Flutter utils for getting the device's location.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^12.0.0
  rxdart: ^0.27.5

  drop:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/drop
  environment:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/environment
  location_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/location_core
  pond:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/pond
  runtime_type:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/type
  style:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/style
  utils:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
