name: reset
description: Flutter utils for resetting the app.

publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.6.0

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  flutter_hooks: ^0.21.1-pre.0
  provider: ^6.0.5

  debug:
    path: ../../../pond/modules/debug
  pond:
    path: ../../../pond/pond
  style:
    path: ../../../style
  utils:
    path: ../../../utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
