name: device_files
description: App Component to view the device files.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_hooks: ^0.21.1-pre.0
  intersperse: ^2.0.0
  path: ^1.8.2

  debug:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/pond/modules/debug
  environment:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/pond/modules/environment
  model:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/model/model
  persistence_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/persistence/persistence_core
  pond:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/pond/pond
  port_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/port/port_core
  port_style:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/port/port_style
  style:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/style
  utils:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/utils/utils

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
