name: device_files
description: App Component to view the device files.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_hooks: ^0.21.1-pre.0
  intersperse: ^2.0.0
  path: ^1.8.2

  asset:
    path: ../../../pond/modules/asset
  debug:
    path: ../../../pond/modules/debug
  environment:
    path: ../../../pond/modules/environment
  model:
    path: ../../../model/model
  persistence_core:
    path: ../../../persistence/persistence_core
  pond:
    path: ../../../pond/pond
  port_core:
    path: ../../../port/port_core
  port_style:
    path: ../../../port/port_style
  share:
    path: ../../../pond/modules/share
  style:
    path: ../../../style
  utils:
    path: ../../../utils/utils

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
