name: flood_cli
description: CLI Flood utils

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  firebase_ops:
    path: ../../pond/modules/firebase_ops
  flood_core:
    path: ../../flood/flood_core
  native_setup:
    path: ../../pond/modules/native_setup
  ops:
    path: ../../pond/modules/ops
  pond_cli:
    path: ../../pond/pond_cli
  release:
    path: ../../pond/modules/release
dev_dependencies:
  lints: ^2.0.0
dependency_overrides:
  vm_service: 13.0.0