// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk5MgWpVwqI1CHCa6y2qH4O6iA4-Z68Bg',
    appId: '1:489232141102:android:ea1b542ad0006e42ad88bf',
    messagingSenderId: '489232141102',
    projectId: 'valet-budget-uat',
    storageBucket: 'valet-budget-uat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiBoJsX4vutYodA_ba8-RLr0cEiOSM0_M',
    appId: '1:489232141102:ios:4e3798d890756f7cad88bf',
    messagingSenderId: '489232141102',
    projectId: 'valet-budget-uat',
    storageBucket: 'valet-budget-uat.appspot.com',
    iosClientId: '489232141102-8bqjnl81lsn4phd1aurhige2qd4b6jt7.apps.googleusercontent.com',
    iosBundleId: 'com.jlogical.valet',
  );
}
