name: ops
description: Adds ops deployments and debugging.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  dart_appwrite: ^12.1.0
  path: ^1.8.0
  rxdart: ^0.28.0

  appwrite_core:
    path: ../../../pond/modules/appwrite_core
  asset_core:
    path: ../../../pond/modules/asset_core
  drop_core:
    path: ../../../pond/modules/drop_core
  environment_core:
    path: ../../../pond/modules/environment_core
  firebase_ops:
    path: ../../../pond/modules/firebase_ops
  log_core:
    path: ../../../pond/modules/log_core
  path_core:
    path: ../../../path_core
  persistence_core:
    path: ../../../persistence/persistence_core
  pond_cli:
    path: ../../../pond/pond_cli
  pond_core:
    path: ../../../pond/pond_core
  task_core:
    path: ../../../pond/modules/task_core
  runtime_type:
    path: ../../../type
  type_core:
    path: ../../../pond/modules/type_core
  utils_core:
    path: ../../../utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6