name: port_style
description: Styled Port fields

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  equatable: ^2.0.5
  file_picker: ^6.2.0
  flutter_hooks: ^0.18.5+1
  provider: ^6.0.5

  persistence_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "location"
      path: packages/persistence/persistence_core
  port:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "location"
      path: packages/port/port
  style:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "location"
      path: packages/style
  utils:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "location"
      path: packages/utils/utils
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6