name: port_style
description: Styled Port fields

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  equatable: ^2.0.5
  file_picker: ^6.2.0
  flutter_hooks: ^0.21.1-pre.0
  intl: ^0.18.0
  number_text_input_formatter: ^1.0.0+8
  phone_number_text_input_formatter: ^0.0.2
  provider: ^6.0.5
  uuid: ^4.1.0

  asset:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/asset
  log:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/log
  persistence_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/persistence/persistence_core
  pond:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/pond
  port:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/port/port
  runtime_type:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/type
  style:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/style
  type_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/type_core
  utils:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/utils/utils
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6