name: drop_core
description: Core module for Drop

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  rxdart: ^0.27.5
  uuid: ^3.0.6

  actions_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/pond/modules/actions_core
  environment_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/pond/modules/environment_core
  model_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/model/model_core
  pond_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/pond/pond_core
  type:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/type
  type_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/pond/modules/type_core
  utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
