name: drop_core
description: Core module for Drop

publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.6.0

version: 0.0.1

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  pool: ^1.5.1
  rxdart: ^0.28.0
  uuid: ^4.1.0

  actions_core:
    path: ../../../pond/modules/actions_core
  asset_core:
    path: ../../../pond/modules/asset_core
  auth_core:
    path: ../../../pond/modules/auth_core
  environment_core:
    path: ../../../pond/modules/environment_core
  log_core:
    path: ../../../pond/modules/log_core
  model_core:
    path: ../../../model/model_core
  persistence_core:
    path: ../../../persistence/persistence_core
  pond_core:
    path: ../../../pond/pond_core
  runtime_type:
    path: ../../../type
  type_core:
    path: ../../../pond/modules/type_core
  utils_core:
    path: ../../../utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.6
