name: jlogical_utils
description: All JLogical utils

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

version: 0.0.1

dependencies:
  jlogical_utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/jlogical_utils_core
  environment:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/modules/environment
  persistence:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/persistence
  pond:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/pond
dev_dependencies:
  lints: ^2.0.0