name: drop
description: Flutter utils for Drop

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  flutter_hooks: ^0.18.5+1
  provider: ^6.0.5
  rxdart: ^0.27.5
  uuid: ^3.0.6

  drop_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/packages/drop_core
  model:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/model/model
  pond:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/pond
  utils:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0