name: drop
description: Flutter utils for Drop

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  equatable: ^2.0.5
  flutter_hooks: ^0.21.1-pre.0
  path: ^1.8.3
  pool: ^1.5.1
  provider: ^6.0.5
  rxdart: ^0.28.0
  uuid: ^4.1.0

  debug:
    path: ../../../pond/modules/debug
  drop_core:
    path: ../../../pond/modules/drop_core
  environment:
    path: ../../../pond/modules/environment
  log:
    path: ../../../pond/modules/log
  model:
    path: ../../../model/model
  persistence:
    path: ../../../persistence/persistence
  pond:
    path: ../../../pond/pond
  port_drop_core:
    path: ../../../pond/modules/port_drop_core
  port_style:
    path: ../../../port/port_style
  style:
    path: ../../../style
  runtime_type:
    path: ../../../type
  type_core:
    path: ../../../pond/modules/type_core
  utils:
    path: ../../../utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
