name: model_component
description: App Component to configure default style of ModelBuilders.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5

  model:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/model/model
  pond:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/pond

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
