name: actions
description: Flutter utils for Actions

publish_to: "none"
resolution: workspace

environment:
  sdk: ^3.6.0

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0

  actions_core:
    path: ../../../pond/modules/actions_core
  pond:
    path: ../../../pond/pond
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
