name: port_core
description: Core for port utils

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  rxdart: ^0.27.5
  uuid: ^4.1.0

  asset_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/pond/modules/asset_core
  persistence_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/persistence/persistence_core
  runtime_type:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/type
  utils_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6