name: style
description: The style system.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  chewie: ^1.8.1
  collection: ^1.16.0
  font_awesome_flutter: ^10.4.0
  flutter_hooks: ^0.21.1-pre.0
  flutter_markdown: ^0.6.8
  flutter_staggered_grid_view: ^0.6.2
  google_fonts: ^6.1.0
  intersperse: ^2.0.0
  intl: ^0.18.0
  multi_dropdown: ^2.1.4
  pattern_formatter: ^3.0.0
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  tinycolor2: ^3.0.1
  transparent_image: ^2.0.1
  video_player: ^2.8.6

  utils:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/utils/utils

dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6

dependency_overrides:
  http: 0.13.5
  win32: ^5.4.0

flutter:
  uses-material-design: true