name: app_icon
description: Automate package to set the app icon.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  image: ^3.0.2

  persistence_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/persistence/persistence_core
  pond_cli:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/pond/pond_cli
  pond_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/pond/pond_core
  utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "3.0"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
dependency_overrides: # Needed because of [dcli] and [interact]
  intl: 0.18.0
  matcher: 0.12.14
  test_api: 0.4.16
  win32: 4.1.0
  path: 1.8.3
  js: 0.6.5