name: jlogical_utils_cli
description: All cli JLogical utils

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  jlogical_utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/jlogical_utils/jlogical_utils_core
  app_icon:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/modules/app_icon
  ops:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/modules/ops
  pond_cli:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/pond_cli
  release:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/modules/release
dev_dependencies:
  lints: ^2.0.0