name: url_bar
description: Flutter module for adding a url bar to navigate throughout the app.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_hooks: ^0.18.5+1

  pond:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/pond
  style:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/style
  utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
dependency_overrides: # Needed because of [dcli] and [interact]
  intl: 0.18.0
  matcher: 0.12.14
  test_api: 0.4.16
  win32: 4.1.0
  path: 1.8.3
  js: 0.6.5