name: port_drop_core
description: Port & Drop Integration

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  equatable: ^2.0.5
  rxdart: ^0.27.5
  uuid: ^3.0.7

  drop_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.2"
      path: packages/pond/modules/drop_core
  pond_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.2"
      path: packages/pond/pond_core
  port_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.2"
      path: packages/port/port_core
  runtime_type:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.2"
      path: packages/type
  type_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.2"
      path: packages/pond/modules/type_core
  utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.2"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6
