name: actions_core
description: Core module for actions.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0

  log_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.0"
      path: packages/pond/modules/log_core
  pond_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.0"
      path: packages/pond/pond_core
  utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.0"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6
