name: release
description: Adds release management.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  version: ^3.0.0
  xcodeproj:
    git:
      url: git@github.com:jaboyc/xcodeproj.git
      ref: "master"

  drop_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/modules/drop_core
  environment_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/modules/environment_core
  persistence_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/persistence/persistence_core
  pond_cli:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/pond_cli
  pond_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/pond_core
  type_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/pond/modules/type_core
  utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6