name: appwrite_app
description: Contains Appwrite-related components.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  rxdart: ^0.27.5

  appwrite: ^11.0.0

  appwrite_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/modules/appwrite_core
  auth_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/modules/auth_core
  drop_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/modules/drop_core
  environment:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/modules/environment
  log_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/modules/log_core
  messaging_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/modules/messaging_core
  path_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/path_core
  pond:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/pond
  pond_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/pond_core
  task_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/pond/modules/task_core
  type:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/type
  utils:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "v3.1"
      path: packages/utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
