name: pond
description: The Pond Framework.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  pond_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/pond_core
  utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/utils/utils_core
  flutter_hooks: ^0.18.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true