name: firebase
description: Contains Firebase-related components.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  rxdart: ^0.28.0

  cloud_firestore: ^5.6.0
  cloud_functions: ^5.2.0
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_crashlytics: ^4.2.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  mime: ^1.0.5
  path: ^1.8.2

  asset:
    path: ../../../pond/modules/asset
  auth_core:
    path: ../../../pond/modules/auth_core
  drop_core:
    path: ../../../pond/modules/drop_core
  environment:
    path: ../../../pond/modules/environment
  log_core:
    path: ../../../pond/modules/log_core
  messaging_core:
    path: ../../../pond/modules/messaging_core
  model_core:
    path: ../../../model/model_core
  persistence:
    path: ../../../persistence/persistence
  pond:
    path: ../../../pond/pond
  pond_core:
    path: ../../../pond/pond_core
  runtime_type:
    path: ../../../type
  utils:
    path: ../../../utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
