name: jlogical_utils
description: All JLogical utils

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

version: 0.0.1

dependencies:
  jlogical_utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/jlogical_utils_core
  environment:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/modules/environment
  environment_banner:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/modules/environment_banner
  focus_grabber:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/modules/focus_grabber
  persistence:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/persistence
  pond:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/pond
  style:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/style
  style_component:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/pond/style_component
  utils:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/utils/utils
dev_dependencies:
  lints: ^2.0.0