name: asset
description: Handles loading and displaying assets.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.16.0
  file_picker: ^6.2.0
  flutter_hooks: ^0.21.1-pre.0
  flutter_image_compress: ^2.3.0
  image_picker: ^1.1.1
  rxdart: ^0.27.5
  video_compress: ^3.1.3

  asset_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/asset_core
  debug:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/debug
  drop:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/drop
  environment:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/modules/environment
  model:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/model/model
  persistence:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/persistence/persistence
  pond:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/pond/pond
  style:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/style
  utils:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.2"
      path: packages/utils/utils
dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
