name: persistence
description: Persistence utils for Flutter.

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  localstorage: ^4.0.1+4
  package_info_plus: ^8.0.0
  path: ^1.8.3
  rxdart: ^0.27.5

  persistence_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/persistence/persistence_core
  utils_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.1"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6