name: example_core
description: A sample command-line application.
version: 0.0.10+9
publish_to: none
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  collection: ^1.16.0
  intl: ^0.18.0
  meta: ^1.8.0
  flood_core:
    git:
      url: "git@github.com:JLogical-Apps/flood.git"
      ref: v4.0
      path: packages/flood/flood_core
  flood_cli:
    git:
      url: "git@github.com:JLogical-Apps/flood.git"
      ref: v4.0
      path: packages/flood/flood_cli
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6
dependency_overrides:
  vm_service: 13.0.0
