name: example_core
description: A sample command-line application.
version: 0.0.7+8
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  collection: ^1.16.0
  intl: ^0.18.0
  meta: ^1.8.0
  jlogical_utils_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/jlogical_utils/jlogical_utils_core
  jlogical_utils_cli:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: "master"
      path: packages/jlogical_utils/jlogical_utils_cli
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6