name: example_core
description: A sample command-line application.
version: 0.0.7+8
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  collection: ^1.16.0
  intl: ^0.18.0
  meta: ^1.8.0
  provider: ^6.0.5
  jlogical_utils_core:
    git:
      url: "git@github.com:jaboyc/jlogical_utils.git"
      ref: v3.0
      path: packages/jlogical_utils/jlogical_utils_core
  jlogical_utils_cli:
    git:
      url: "git@github.com:jaboyc/jlogical_utils.git"
      ref: v3.0
      path: packages/jlogical_utils/jlogical_utils_cli
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6
dependency_overrides:
  intl: 0.18.0
  win32: 4.1.0
  path: 1.8.3
  js: 0.6.5
  posix: 5.0.0
