name: model
description: Model utils for Flutter.

publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

version: 0.0.1

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.16.0
  flutter_hooks: ^0.18.5+1
  provider: ^6.0.5

  model_core:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/model/model_core
  style:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/style
  utils:
    git:
      url: git@github.com:jaboyc/jlogical_utils.git
      ref: master
      path: packages/utils/utils
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4