name: environment_core
description: Core module for Environment configs

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  collection: ^1.16.0
  equatable: 2.0.5

  persistence_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "location"
      path: packages/persistence/persistence_core
  pond_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "location"
      path: packages/pond/pond_core
  utils_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "location"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6
