name: persistence_core
description: Core for persistence utils

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

version: 0.0.1

dependencies:
  archive: ^3.6.1
  collection: ^1.16.0
  csv: ^6.0.0
  json2yaml: ^3.0.0
  path: ^1.8.3
  rxdart: ^0.27.5
  synchronized: ^3.1.0+1
  watcher: ^1.1.0
  yaml: ^3.1.1

  model_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.3"
      path: packages/model/model_core
  utils_core:
    git:
      url: git@github.com:JLogical-Apps/flood.git
      ref: "v4.3"
      path: packages/utils/utils_core
dev_dependencies:
  lints: ^2.0.0
  test: 1.24.6